export interface Product {
  id: string;
  name: string;
  hindiName?: string;
  category: "chicken" | "mutton" | "fish" | "desi-chicken" | "eggs" | "marinated";
  categoryLabel: string;
  description: string;
  pieces?: string;
  serves?: string;
  badge?: string;
  isBestseller?: boolean;
  image: string;
  images?: string[];
  netWeight: string;
  grossWeight?: string;
  price: number;
  originalPrice: number;
  rating: number;
  ratingCount: number;
  inStock: boolean;
  cutType?: string;
  cookingTime?: string;
  benefits?: string[];
}

export interface Category {
  id: string;
  slug: "all" | "chicken" | "mutton" | "fish" | "desi-chicken" | "eggs" | "marinated";
  name: string;
  tagline: string;
  icon: string;
  image: string;
}

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    slug: "all",
    name: "All Items",
    tagline: "Fresh Daily Catch & Cuts",
    icon: "🥩",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "cat-2",
    slug: "chicken",
    name: "Fresh Chicken",
    tagline: "Tender, antibiotic-free & cut fresh",
    icon: "🍗",
    image: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "cat-3",
    slug: "mutton",
    name: "Rich Mutton",
    tagline: "Farm-raised goat, tender curry cuts",
    icon: "🍖",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "cat-4",
    slug: "fish",
    name: "Fish & Seafood",
    tagline: "Freshwater & sea fish, cleaned & gutted",
    icon: "🐟",
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "cat-5",
    slug: "desi-chicken",
    name: "Desi Chicken",
    tagline: "Free-range country chicken (देसी मुर्गा)",
    icon: "🐓",
    image: "https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: "cat-6",
    slug: "eggs",
    name: "Farm Eggs",
    tagline: "Classic white, brown & country eggs",
    icon: "🥚",
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=400&q=80",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-chk-5",
    name: "Chicken Lollipop 1kg",
    hindiName: "चिकन लॉलीपॉप (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "You will get 20 to 25 succulent and perfectly shaped pieces in a Kg. Every piece is precisely cut by stainless steel cutting machines and washed in purified RO water.",
    pieces: "20-25 Pieces",
    serves: "4-5 People",
    badge: "Special Cut",
    isBestseller: true,
    image: "https://media.istockphoto.com/id/1255992885/photo/raw-lollipop-chicken-wings.jpg?s=612x612&w=0&k=20&c=0Y2W2Mqy6YdN3ZgMvrMpOPYVbD4lHZyKO5nBA16zDd0=",
    images: [
      "https://images.unsplash.com/photo-1527477321055-43615b629c95?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "1kg",
    grossWeight: "1.05kg",
    price: 285,
    originalPrice: 300,
    rating: 4.8,
    ratingCount: 388,
    inStock: true,
    cutType: "Lollipop Frenched Cut",
    cookingTime: "15-20 Mins (Fry/Grill)",
    benefits: [
      "20 to 25 frenched winglet pieces per pack",
      "Cut after you place order (0% frozen)",
      "RO water sanitized & packed in food-grade tray",
      "Ideal for crispy starters, Schezwan lollipops & BBQ",
    ],
  },
  {
    id: "prod-chk-1",
    name: "Fresh Chicken Curry Cut (Skinless)",
    hindiName: "ताज़ा चिकन करी कट",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Juicy bone-in & boneless pieces of fresh chicken. Cut right after you place your order for unmatched freshness.",
    pieces: "12-16 Pieces",
    serves: "3-4 People",
    badge: "Bestseller",
    isBestseller: true,
    image: "https://www.giggsmeat.com/wp-content/uploads/2020/10/rsz_chicken_curry_cut.jpg",
    images: [
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "520g",
    price: 139,
    originalPrice: 170,
    rating: 4.8,
    ratingCount: 342,
    inStock: true,
    cutType: "Curry Cut",
    cookingTime: "25-30 Mins",
    benefits: ["Even blend of breast & leg pieces", "High protein & natural tenderness", "RO washed"],
  },
  {
    id: "prod-chk-2",
    name: "Fresh Chicken Breast (Boneless)",
    hindiName: "बोनलेस चिकन ब्रेस्ट",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Lean, tender and high protein boneless fillets. Ideal for grilling, salads, butter chicken or gym diet.",
    pieces: "2-4 Fillets",
    serves: "2-3 People",
    badge: "High Protein",
    isBestseller: true,
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "510g",
    price: 179,
    originalPrice: 220,
    rating: 4.9,
    ratingCount: 280,
    inStock: true,
    cutType: "Boneless Fillet",
    cookingTime: "12-15 Mins",
    benefits: ["Zero fat & zero bones", "31g protein per 100g", "Pre-trimmed & ready to cook"],
  },
  {
    id: "prod-chk-3",
    name: "Chicken Biryani Cut (Large Pieces)",
    hindiName: "बिरयानी कट चिकन",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Specially selected large drumsticks, thigh and breast pieces crafted specifically for authentic dum biryani.",
    pieces: "6-8 Large Pieces",
    serves: "4 People",
    badge: "Biryani Special",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "1kg",
    grossWeight: "1.05kg",
    price: 269,
    originalPrice: 320,
    rating: 4.7,
    ratingCount: 195,
    inStock: true,
    cutType: "Large Cut",
    cookingTime: "40 Mins (Dum Cooking)",
    benefits: ["Large juicy cuts hold marinade perfectly", "Juicy texture under steam", "Cut fresh"],
  },
  {
    id: "prod-chk-4",
    name: "Chicken Whole Leg (Thigh & Drumstick)",
    hindiName: "चिकन लेग पीस",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Tender skinless whole leg pieces with bone. Best for slow-cooked tandoori roasts, curry and fries.",
    pieces: "3-4 Pieces",
    serves: "2-3 People",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "530g",
    price: 159,
    originalPrice: 195,
    rating: 4.8,
    ratingCount: 142,
    inStock: true,
    cutType: "Leg Piece",
    cookingTime: "25 Mins",
    benefits: ["Succulent dark meat flavor", "Ideal for tandoor & roast", "Trimmed of excess fat"],
  },
  {
    id: "prod-mut-1",
    name: "Fresh Goat Mutton Curry Cut (Khaste Mutton)",
    hindiName: "ताज़ा बकरे का मीट करी कट",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Premium pasture-raised young goat meat with equal blend of bone and meat chunks. Freshly cut on order.",
    pieces: "14-18 Pieces",
    serves: "3-4 People",
    badge: "Chef's Choice",
    isBestseller: true,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "540g",
    price: 439,
    originalPrice: 499,
    rating: 4.9,
    ratingCount: 418,
    inStock: true,
    cutType: "Curry Cut",
    cookingTime: "45-60 Mins",
    benefits: ["Young grass-fed Khasi goat meat", "Even fat-to-meat ratio", "Mouth-melting curry texture"],
  },
  {
    id: "prod-mut-2",
    name: "Prime Mutton Shoulder Cut (Bone-In)",
    hindiName: "मटन शोल्डर कट",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Rich, tender shoulder cuts known for high marbling and melt-in-mouth texture when slow-cooked in gravy.",
    pieces: "12-15 Pieces",
    serves: "3 People",
    badge: "Extra Tender",
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "520g",
    price: 479,
    originalPrice: 530,
    rating: 4.9,
    ratingCount: 164,
    inStock: true,
    cutType: "Shoulder Cut",
    cookingTime: "50 Mins",
    benefits: ["High marbling", "Tender bone marrow flavor", "Finest cut for Rogan Josh"],
  },
  {
    id: "prod-mut-3",
    name: "Fine Goat Mutton Keema (Mince)",
    hindiName: "बकरे का मटन कीमा",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Finely ground fresh mutton from prime boneless cuts. Free of excess fat, ideal for kebabs and keema matar.",
    pieces: "Ground Mince",
    serves: "3-4 People",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "510g",
    price: 499,
    originalPrice: 560,
    rating: 4.8,
    ratingCount: 96,
    inStock: true,
    cutType: "Keema",
    cookingTime: "25 Mins",
    benefits: ["100% pure meat mince", "Zero grit or sinew", "Ideal for Shammi Kebabs & Keema Pav"],
  },
  {
    id: "prod-fsh-1",
    name: "Fresh Rohu Fish - Bengali Cut (Cleaned)",
    hindiName: "रोहू मछली (बंगाली कट)",
    category: "fish",
    categoryLabel: "Fish & Seafood",
    description: "Fresh river catch Rohu, scaled, gutted, and cut into neat steaks and head for delicious fish curry.",
    pieces: "6-8 Steaks + Head",
    serves: "2-3 People",
    badge: "Daily Catch",
    isBestseller: true,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "650g",
    price: 189,
    originalPrice: 230,
    rating: 4.7,
    ratingCount: 220,
    inStock: true,
    cutType: "Steaks (Bengali Cut)",
    cookingTime: "15-20 Mins",
    benefits: ["River fresh daily catch", "Scaled and gutted thoroughly", "Zero chemical preservatives"],
  },
  {
    id: "prod-fsh-2",
    name: "Catla Fish - Medium Steaks (Cleaned)",
    hindiName: "कतला मछली कट",
    category: "fish",
    categoryLabel: "Fish & Seafood",
    description: "Sweet water Catla steaks. Thoroughly washed with RO water and vacuum packed with temperature control.",
    pieces: "7-9 Steaks",
    serves: "3-4 People",
    image: "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "500g",
    grossWeight: "620g",
    price: 199,
    originalPrice: 240,
    rating: 4.6,
    ratingCount: 130,
    inStock: true,
    cutType: "Curry Cut",
    cookingTime: "15 Mins",
    benefits: ["Sweet water taste", "Rich in Omega 3", "Cleaned & gutted"],
  },
  {
    id: "prod-fsh-3",
    name: "Fresh Sea Prawns - Tail On (Cleaned & Deveined)",
    hindiName: "ताज़ा झींगा (प्रॉन्स)",
    category: "fish",
    categoryLabel: "Fish & Seafood",
    description: "Large succulent prawns, deshelled and deveined for effortless cooking. No chemical preservatives.",
    pieces: "20-25 Prawns",
    serves: "2-3 People",
    badge: "Ready to Cook",
    image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "250g",
    grossWeight: "400g",
    price: 289,
    originalPrice: 340,
    rating: 4.9,
    ratingCount: 184,
    inStock: true,
    cutType: "Deveined",
    cookingTime: "6-8 Mins",
    benefits: ["100% Deveined & peeled", "Sweet juicy texture", "High in protein & zinc"],
  },
  {
    id: "prod-desi-1",
    name: "Original Desi Country Chicken (देसी मुर्गा)",
    hindiName: "असली देसी मुर्गा करी कट",
    category: "desi-chicken",
    categoryLabel: "Desi Chicken",
    description: "Authentic naturally reared free-range country chicken. Firm texture, earthy aroma, and deep traditional flavour.",
    pieces: "12-16 Pieces",
    serves: "3-4 People",
    badge: "100% Free Range",
    isBestseller: true,
    image: "https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "1kg",
    grossWeight: "1.2kg",
    price: 469,
    originalPrice: 550,
    rating: 4.9,
    ratingCount: 310,
    inStock: true,
    cutType: "Skinless Country Cut",
    cookingTime: "45-55 Mins",
    benefits: ["Free-range farm birds", "Deep earthy flavour", "Zero hormones or growth steroids"],
  },
  {
    id: "prod-egg-1",
    name: "Farm Fresh Classic White Eggs (Pack of 12)",
    hindiName: "फार्म फ्रेश अंडे (12 पीस)",
    category: "eggs",
    categoryLabel: "Eggs",
    description: "Freshly harvested antibiotic-free table eggs with vibrant yellow yolk. Cleaned and safe packaging.",
    pieces: "12 Eggs",
    serves: "Daily Essentials",
    badge: "Daily Fresh",
    image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "12 pcs",
    price: 99,
    originalPrice: 120,
    rating: 4.8,
    ratingCount: 520,
    inStock: true,
    cutType: "Tray Pack",
    benefits: ["Fresh harvest daily", "Strong shells & rich yolk", "Hygienically sorted"],
  },
  {
    id: "prod-egg-2",
    name: "Nutritious Desi Brown Eggs (Pack of 6)",
    hindiName: "देसी मुर्गी के भूरे अंडे (6 पीस)",
    category: "eggs",
    categoryLabel: "Eggs",
    description: "Rich in omega-3 and proteins from naturally forage-fed hens. Deep orange yolk and thicker shells.",
    pieces: "6 Eggs",
    serves: "High Nutrition",
    badge: "Desi Organic",
    image: "https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "6 pcs",
    price: 85,
    originalPrice: 105,
    rating: 4.9,
    ratingCount: 245,
    inStock: true,
    cutType: "Tray Pack",
    benefits: ["Omega-3 fortified", "Deep golden orange yolk", "From naturally forage-fed hens"],
  },
  {
    id: "prod-egg-3",
    name: "Family Saver Fresh White Eggs (Crate of 30)",
    hindiName: "फार्म फ्रेश अंडे क्रेट (30 पीस)",
    category: "eggs",
    categoryLabel: "Eggs",
    description: "Economy wholesale family pack of 30 farm-fresh table eggs. Clean, intact, and safe crate packaging.",
    pieces: "30 Eggs",
    serves: "Family Saver",
    badge: "Value Crate",
    image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "30 pcs",
    price: 230,
    originalPrice: 270,
    rating: 4.9,
    ratingCount: 410,
    inStock: true,
    cutType: "Crate Pack",
    benefits: ["Best price per egg", "Daily fresh sorting", "Safe shockproof packaging"],
  },
  // Storefront Cuts
  {
    id: "chicken-curry-cut-1kg",
    name: "Curry Cut 1 Kg",
    hindiName: "चिकन करी कट (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Mix of bone-in & boneless prime pieces ideal for slow Sunday gravies. Cut after order from healthy broiler chickens, sanitized in RO water.",
    pieces: "14-16 Pieces",
    serves: "4-5 People",
    badge: "Best Seller",
    isBestseller: true,
    image: "https://www.giggsmeat.com/wp-content/uploads/2020/10/rsz_chicken_curry_cut.jpg",
    images: [
      "https://lh3.googleusercontent.com/aida/AEtjO1U14IRgfExyqM7RqzBVytYg4RKCip9oYuxZcI-LzlWKFL9AuxhdIvNT7i5pB2BWmYvPKPLXmiX14Acg637SmRFdcAqvmAmZ0AiFrF9rFqGEnX4veNvb9Ui1HrUDGcCZIoI2HITYg22oRubCfHHLTmmv3uowZ8wXkb-zXIcTIA8JInpgLLGx87YIE_YJ7fobrDjw1sXGJV_nM2q-GYdLKj1jgEC54kSi-_suQxMZrUWcARlYbxyUSbSW8A",
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80",
    ],
    netWeight: "1000g",
    grossWeight: "1050g",
    price: 280,
    originalPrice: 300,
    rating: 4.9,
    ratingCount: 420,
    inStock: true,
    cutType: "Bone-in Curry Cut",
    cookingTime: "30-35 Mins",
    benefits: ["Balanced leg & breast portions", "RO-purified wash", "Never frozen (0-4°C)"],
  },
  {
    id: "chicken-lollipop-1kg",
    name: "Chicken Lollipop 1kg",
    hindiName: "चिकन लॉलीपॉप (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Clean frenched wingettes and drumettes sculpted for crispy frying and appetizers. 18-20 pieces per pack.",
    pieces: "18-20 Pieces",
    serves: "4-5 People",
    badge: "Snack Special",
    isBestseller: true,
    image: "https://media.istockphoto.com/id/1255992885/photo/raw-lollipop-chicken-wings.jpg?s=612x612&w=0&k=20&c=0Y2W2Mqy6YdN3ZgMvrMpOPYVbD4lHZyKO5nBA16zDd0=",
    images: [
      "https://lh3.googleusercontent.com/aida/AEtjO1UNRNgmV2ikFoRKYpfYTm9xvRRnEhapfsFVLdQpMS-47HWqnVxP_kRPZlPw3PPgVr98slASBEc8zqu_22HbXOPYKMnmgqNcXSP77KPRXX5Pw87wiY_D5JCvgIsdANRI7f7o9XrVvfwEAiL93bx1ofDsG8vixmmQsXQ8t7NZ3AVX1eaWvAk5FT8r0orT-GsbHD5iIcRu7ibbPCfCxr6fYbdui8tkYvfAJX4dg8Ed-ZITWZYjXfeZKFtNbA",
    ],
    netWeight: "1000g",
    price: 285,
    originalPrice: 300,
    rating: 4.8,
    ratingCount: 310,
    inStock: true,
    cutType: "Frenched Wing Cut",
    cookingTime: "15-20 Mins",
    benefits: ["Hand-frenched by master butchers", "Crisp fry ready", "Zero freezer storage"],
  },
  {
    id: "chicken-drumstick-1kg",
    name: "Chicken Drumsticks 1 Kg",
    hindiName: "चिकन ड्रमस्टिक्स",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Plump lower leg cuts, skinless and perfectly trimmed for juicy grilling, tandoori, and biryanis.",
    pieces: "8-10 Legs",
    serves: "4 People",
    badge: "Biryani Essential",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1XEXYsorgCDQfJeF5rjP0qJL7pIgbOW5IT5JI8Da98U-AUlkyNhvKUm9VItAhsMOm--rHS2OUkkCSTj5ceAlZF409KUkUMZIhB0Mo4OnpYJ4ZGRx2Sm5TYVZ8bKdQ6g9ByjaIjE9Nmx3IL3WfH-96LZk9CnmOm0N9pRW5PUmB3aPuPMfyEMGvdq9WJd24NLFG5GhZKm1d9cK-l_6VjW9pxi_wR0URHcXhrILvt7HRIUr38HsZvxKWxjQQ",
    netWeight: "1000g",
    price: 350,
    originalPrice: 370,
    rating: 4.9,
    ratingCount: 220,
    inStock: true,
    cutType: "Drumstick",
    cookingTime: "25-30 Mins",
    benefits: ["Juicy meat on single bone", "Pre-trimmed tendons", "High collagen & protein"],
  },
  {
    id: "chicken-wings-1kg",
    name: "Chicken Wings 1kg",
    hindiName: "चिकन विंग्स",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Skin-on wings with unmatched richness and flavor when baked, barbecued, or tossed in spicy glazes.",
    pieces: "12-14 Wings",
    serves: "3-4 People",
    badge: "Barbecue Cut",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1VTFHCuK-cFltmasMDFqLaqzzp8aau4eW-CQ3E1pwV5pyu4HFPAlx-FzqMPQga4Y1jrJ9ZMVHqquoxDjhvtY8AeloOqNVnycThWV4uL_Y9f9CpaJ2THNQOd8ce1f_uVaWDRkfaIvlQeX_ngrlwIVMH1SHVQFuHNuVxzW72ULVWUeu-MMW16ZvGzRm3yhaVJ1pAm_PLCWqZipulbYKSHiGlNfuCIUQUPWDEzNIHbRRFF5_Mor1PlB2gnSw",
    netWeight: "1000g",
    price: 245,
    originalPrice: 265,
    rating: 4.7,
    ratingCount: 160,
    inStock: true,
    cutType: "Skin-on Wings",
    cookingTime: "20-25 Mins",
    benefits: ["Natural skin fat keeps meat tender", "Crispy finish", "Party favourite"],
  },
  {
    id: "chicken-ran-1kg",
    name: "Chicken Ran (Full Leg) 1kg",
    hindiName: "चिकन रान (फुल लेग)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Combined thigh and drumstick with skin off for deep tandoori roasts, pot roasting, or hearty slow curries.",
    pieces: "4 Full Legs",
    serves: "4 People",
    badge: "Whole Leg",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1Uu1e3KgA9dUDsxfEpkpMzOM---tbHiu8Dhsm1Xe5FOm0Qhm-h8vrDCUbAYA8FlmS6BTLnp_g3qUFD2mY1lIeLzXktzih8hyMDLIqgWS6_yZeOY_u9_5sApLqlVC0La2JzJG4y-PqnGiXQkBNpp3ATxm9SFnf98KxNZkBUTp7u1yr2mxutai2Y5SwJAyPmGjRlIoHGA4ySsBiMRrUE6WGK-9QUJwitn5OWQpR0LHlHscKhMNYj8o3hr",
    netWeight: "1000g",
    price: 290,
    originalPrice: 310,
    rating: 4.8,
    ratingCount: 190,
    inStock: true,
    cutType: "Full Leg Cut",
    cookingTime: "30-35 Mins",
    benefits: ["Thigh tenderness + drumstick flavour", "Perfect for grilling", "Antibiotic residue-free"],
  },
  {
    id: "chicken-keema-1kg",
    name: "Chicken Keema 1kg",
    hindiName: "चिकन कीमा (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Finely minced breast & thigh meat. Double ground and perfectly seasoned for parathas, samosas & koftas.",
    pieces: "100% Minced Meat",
    serves: "4-5 People",
    badge: "Double Ground",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1W2TxnZd-j5N3uAWjH4mAamsuvHSfd033KiN1ZoiYINftrPAYCNqIsnh0JA0LuOImdSgY5Ojswk_2EdN4C-8Sp9XmnBRRMEbC7UIOG9gem2xcb-kuy8ZrDzpV-k78-4Bs3WnNi3rwjPhZ2tOniXZ1EQ7yALbz5Txl3RkBLaJPQI715YOOb4ZOShLUs4HTB90nd5o1Ut--fmP6-RCCCYGxd1_7QEiPfbToL93q_XHS1lniwTgGaUVYOvaQ",
    netWeight: "1000g",
    price: 370,
    originalPrice: 395,
    rating: 4.9,
    ratingCount: 275,
    inStock: true,
    cutType: "Minced Keema",
    cookingTime: "15-20 Mins",
    benefits: ["Zero cartilage or gristle", "Fine even texture", "High lean protein"],
  },
  {
    id: "chicken-with-skin-whole-1kg",
    name: "Chicken With Skin Whole 1kg",
    hindiName: "चिकन विथ स्किन",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Retains natural skin fats for maximum moisture in oven roasting or grill. Cleaned, gutted, and dressed.",
    pieces: "Whole Dressed Bird",
    serves: "4 People",
    badge: "Crispy Skin",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1V-89ZaQuCvaTiSu7alVkUqFPb6_9nLy5WZ5Tqyc17o0MWSCvVrGa3vcymUzwPXXVrneSWrDWjTKjXQStBVzFGsgP493leBXmStPHFCJEZhu_pRLvseo5ePa01kic2C8BF8KTEH-OUX62_cWeW-aj6ksFlBH_2FjDiUkX4Fsk3YiAM-JHxwqgGGde9RDsUnY-TltA9011CuROGiWQQX0Ki82SLlb9aUiINpchSZ_z6m2h41wfV9GzUL",
    netWeight: "1000g",
    price: 280,
    originalPrice: 280,
    rating: 4.8,
    ratingCount: 140,
    inStock: true,
    cutType: "Whole Dressed with Skin",
    cookingTime: "45-50 Mins",
    benefits: ["Crispy roasted skin", "Seals in natural juices", "Traditional village roast profile"],
  },
  {
    id: "mutton-curry-cut-1kg",
    name: "Mutton 1Kg (Curry Cut)",
    hindiName: "ताज़ा मटन करी कट (१ किग्रा)",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Balanced mix of bone-in shank, shoulder, and ribs from young country goat. Naturally grass-fed in Jharkhand.",
    pieces: "20-25 Pieces",
    serves: "4-6 People",
    badge: "Prime Cut",
    isBestseller: true,
    image: "https://lh3.googleusercontent.com/aida/AEtjO1V-XpmCoX5V0ku0QhROALLZlcULVA9vr8G1k2fa8EW68uv-gavSPVsEPypHbhiZC-ddjgMlOi9Fz5g3qmVu5dRRwIknVc7PXcGHahULjyuFPCCi7WxfPjaVzjiU6eu32azkVyNQlaAgocRPMLJOUS1aILr8jA34EpLcZ8DYTyxcvcAGm0hFid9qKInhMY5iNMDN76WQIjTMWbEbvYtzKkgBWHN_2qfWCzUfkD4TAVnKR5UZZ1M73FkPig",
    netWeight: "1000g",
    price: 900,
    originalPrice: 1000,
    rating: 4.9,
    ratingCount: 380,
    inStock: true,
    cutType: "Country Goat Curry Cut",
    cookingTime: "45-60 Mins",
    benefits: ["Naturally grass-fed country goat", "Bone marrow richness", "Cut fresh post order"],
  },
  {
    id: "mutton-curry-cut-500g",
    name: "Mutton 500gm (Curry Cut)",
    hindiName: "मटन करी कट (५०० ग्राम)",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Hand-chopped into bite-size pieces. Ideal for rich Rogan Josh, korma or stew for a couple or small family.",
    pieces: "10-12 Pieces",
    serves: "2-3 People",
    badge: "Portion Pack",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1WpEtu-3k6GTNT_z8ePCWuVlJbQQtgzfbHBeFIPPpCGD134MLEowkQeotQeTT29Eml-5oCj-F0EfFu-pCyh3C6hWuw7GeyPbwY_wH5a9Pirk-O6zt_QYPz87ajm62wEHK7pVVtBHC3EvOfVjZZJjSl9wAZ7MJuHbVAHatzNch9UGf6Jjrk_7PZWWiSW8u9LepfjTcmDZmtWcSa1WABtGmRYQV7nyxo0N2daD1kTINisEiWW12mp29gBBQ",
    netWeight: "500g",
    price: 500,
    originalPrice: 550,
    rating: 4.8,
    ratingCount: 290,
    inStock: true,
    cutType: "Country Goat Curry Cut",
    cookingTime: "45-55 Mins",
    benefits: ["Tender shoulder and rib mix", "Hygienically prepped", "0% frozen storage"],
  },
  {
    id: "mutton-curry-cut-750g",
    name: "Mutton 750gm (Family Pack)",
    hindiName: "मटन करी कट (७५० ग्राम)",
    category: "mutton",
    categoryLabel: "Mutton",
    description: "Finely portioned with rib chops, shank, and marrow pieces for rich flavour profile and tender texture.",
    pieces: "16-18 Pieces",
    serves: "3-4 People",
    badge: "Family Cut",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1V-XpmCoX5V0ku0QhROALLZlcULVA9vr8G1k2fa8EW68uv-gavSPVsEPypHbhiZC-ddjgMlOi9Fz5g3qmVu5dRRwIknVc7PXcGHahULjyuFPCCi7WxfPjaVzjiU6eu32azkVyNQlaAgocRPMLJOUS1aILr8jA34EpLcZ8DYTyxcvcAGm0hFid9qKInhMY5iNMDN76WQIjTMWbEbvYtzKkgBWHN_2qfWCzUfkD4TAVnKR5UZZ1M73FkPig",
    netWeight: "750g",
    price: 750,
    originalPrice: 800,
    rating: 4.9,
    ratingCount: 155,
    inStock: true,
    cutType: "Country Goat Curry Cut",
    cookingTime: "45-60 Mins",
    benefits: ["Prime cuts selection", "RO washed before packing", "Rich flavour"],
  },
  {
    id: "rohu-fish-1kg",
    name: "Local Rohu Fish 1 Kg",
    hindiName: "लोकल रोहू मछली (१ किग्रा)",
    category: "fish",
    categoryLabel: "Fish",
    description: "Whole cleaned sweetwater Rohu cut into uniform round steaks and head pieces. Descaled and washed in potable water.",
    pieces: "8-10 Steaks",
    serves: "4 People",
    badge: "Bengali Cut",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1VfFFoFe5gIVjAuAwoM0pUShBeiwZTgnmSjowL9yOjVP0LnK0yXZAY8O1U78Prxarny6htWvDGuULPb49rt2FyrsEkh6OtOJeR3pGIvikgQeEIWIo5k6sEE8IPVjcU-JRtropCjAveFMOmH6lfFIx7hiTgyQXRW0b0qgYC0NP0caxooqfQX1eN8NgYtEzgATics8qTPpTYe6GYbXQ3tlPcm4c-oDw9OfhsWdltmHa38gu6PQ6doutFz",
    netWeight: "1000g",
    price: 280,
    originalPrice: 350,
    rating: 4.8,
    ratingCount: 310,
    inStock: true,
    cutType: "Round Steaks",
    cookingTime: "10-15 Mins",
    benefits: ["Daily sunrise catch", "Zero formalin guaranteed", "Descaled & cleaned"],
  },
  {
    id: "rohu-fish-500g",
    name: "Local Rohu Fish 500gm",
    hindiName: "लोकल रोहू मछली (५०० ग्राम)",
    category: "fish",
    categoryLabel: "Fish",
    description: "Tender freshwater Rohu fish center slices. Cleaned with RO water, ready to marinate and fry or curry.",
    pieces: "5-6 Rings",
    serves: "2 People",
    badge: "Center Steaks",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1VfFFoFe5gIVjAuAwoM0pUShBeiwZTgnmSjowL9yOjVP0LnK0yXZAY8O1U78Prxarny6htWvDGuULPb49rt2FyrsEkh6OtOJeR3pGIvikgQeEIWIo5k6sEE8IPVjcU-JRtropCjAveFMOmH6lfFIx7hiTgyQXRW0b0qgYC0NP0caxooqfQX1eN8NgYtEzgATics8qTPpTYe6GYbXQ3tlPcm4c-oDw9OfhsWdltmHa38gu6PQ6doutFz",
    netWeight: "500g",
    price: 145,
    originalPrice: 200,
    rating: 4.7,
    ratingCount: 180,
    inStock: true,
    cutType: "Center Slices",
    cookingTime: "10-15 Mins",
    benefits: ["Firm sweet flesh", "Hygienic tray pack", "Rich in Omega-3"],
  },
  {
    id: "chicken-liver-1kg",
    name: "Chicken Liver 1 Kg",
    hindiName: "चिकन कलेजी (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Rich in iron, cleaned and portioned fresh chicken liver. Excellent for liver fry or spiced masala gravy.",
    pieces: "Portioned Pieces",
    serves: "4 People",
    badge: "High Iron",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1XzvcaeOH9nTHzVUinepJYQIwnsfZZOepX1jRYAfuyvIpLGu93x2ZmCQo52becW2q34ANvzhDL6MFn7LWBzwK5DaMliTgdZb9Vp6VR1Fk2EXPAqVHKR48ZeUQzLTa7zWKQyhVjJj__YDHLxIWgkKbogvTIvg4U5ngY4eXisUnsP9adJsKKfp2c0g2ckloVEf6VjmpOEaEdwvj6aNgdxHpsB7cty010vHxjQoDXXbZjcLi3DEbKIw962pA",
    netWeight: "1000g",
    price: 265,
    originalPrice: 300,
    rating: 4.8,
    ratingCount: 140,
    inStock: true,
    cutType: "Cleaned Liver",
    cookingTime: "12-15 Mins",
    benefits: ["High iron and vitamin A", "Carefully trimmed", "No bile bitterness"],
  },
  {
    id: "chicken-whole-1kg",
    name: "Chicken Whole 1kg",
    hindiName: "साबुत चिकन (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Dressed, gutted, pristine whole bird with skin off. Ideal for Sunday whole roasts, biryanis, or home portioning.",
    pieces: "Whole Bird",
    serves: "4 People",
    badge: "Whole Cut",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1XAFxevdds-xTIROk3LyLMXddl5eWBMyQGY0HcStRmGal_wzkkG14iM-jeWRAVQhBvdW3v0y15C2iVCMyQbNwENbDtwCXyTaoSEwprZIMCKCKlxNByrrhlvJEItq6xOvaLXZcEM7eNSBSOjOUlgVv0wwfc6PqAFeX2xFAbIO0bvjl1Uj_UDmVd4AN5Bg7ECMkckAJsAbWC8G8jApqI_InXFHz_8MtjDKtaDtYMCgC5b8PDJDH1KElSpHw",
    netWeight: "1000g",
    price: 280,
    originalPrice: 300,
    rating: 4.9,
    ratingCount: 215,
    inStock: true,
    cutType: "Whole Dressed Skinless",
    cookingTime: "40-50 Mins",
    benefits: ["Complete bird dressed cleanly", "Antibiotic-free broiler", "Hygienically handled"],
  },
  {
    id: "chicken-boneless-strips-1kg",
    name: "Chicken Boneless Strips 1kg",
    hindiName: "चिकन बोनलेस स्ट्रिप्स (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Tender tenderloin & breast strips. 100% lean white meat, zero bone, trimmed and sliced for chicken fingers or wraps.",
    pieces: "Tender Strips",
    serves: "4-5 People",
    badge: "Gym & Diet",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1U9gWcuOnnFzi-kuWO6LV6udpXTPTtM5NUGobT9ckutlUjs8jGUzsC2gl13ZV2Db3W6tAiIOH7_4kw0_wQW2CU_rmRaVkHs80wgupRc5wOXINypj_9ZJZdtLsXXSR9Z2ljmEa8njlkuIUwKcAohsAzeIHu7Ok0o49ox1j1oVF-pUfUgIpOcaXDfbw8IocV-Yto2hUP2knBOgjjP71n7SkzV01QFOVXsoYkuhIhdTq7rGEdEpJPFXmpR",
    netWeight: "1000g",
    price: 370,
    originalPrice: 420,
    rating: 4.9,
    ratingCount: 340,
    inStock: true,
    cutType: "Boneless Strips",
    cookingTime: "10-12 Mins",
    benefits: ["Zero bones, zero skin", "Over 30g protein / 100g", "Ready to cook"],
  },
  {
    id: "chicken-boneless-strips-500g",
    name: "Boneless Strips 500gm",
    hindiName: "चिकन बोनलेस स्ट्रिप्स (५०० ग्राम)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Crispy fry & stir-fry ready cuts. High protein lean chicken breast cut into uniform cooking strips.",
    pieces: "Uniform Strips",
    serves: "2-3 People",
    badge: "Portion Pack",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1WKENZxOoZOp7uzm1aUWbLU2CZ2RFpxuUvjgVLhiLy27qgPZFiXEKNj1nDI2TuqcILqR_EQxvdDIBeiWkQLnHxczUUQm74xr_hD9kHm9pZWPgd7EXDhzYhqBZSoqKne8QSkNAutN2oZ1FZ72f_KXwUY3ek7Vs6Z2SaK_YY40sRtBVwXzuztKEFT_nkehiuKOXxOJ7bXoJEr6Aq96fIslt4Ep-zRyvmBOHijtATE-bPngd4J_TLJaZvhMw",
    netWeight: "500g",
    price: 200,
    originalPrice: 225,
    rating: 4.8,
    ratingCount: 220,
    inStock: true,
    cutType: "Boneless Strips",
    cookingTime: "10-12 Mins",
    benefits: ["Convenient portion pack", "Low calorie high protein", "Quick cooking"],
  },
  {
    id: "leg-boneless-1kg",
    name: "Leg Boneless 1kg",
    hindiName: "लेग बोनलेस (१ किग्रा)",
    category: "chicken",
    categoryLabel: "Chicken",
    description: "Succulent thigh boneless meat. Tender, juicy and stays moist in tikkas, butter chicken, and barbecues.",
    pieces: "Boneless Thigh Cubes",
    serves: "4-5 People",
    badge: "Tikka & Kabab",
    image: "https://lh3.googleusercontent.com/aida/AEtjO1VMrDA-7mgMHM47GjuN6HPLWNvUrvz3JMJr8LnRAR9O-KI8pwRQ6dzzoeLVvDcc_Y0hyDAjSrLSa29KrBBK0Th4eoQayWlThUOLK-ychjspZ7IbaoxkuIEthOeRUXWONgd9nPZJy4_EBNX8_KyRGM7iRELCB9zY5xxr4itXHDRMHJLLU9nmMfDrSLi7JdcLHlzXzWw2fLVtHRGxhZVI4aINcX9ULM98uallUdE-HoLjtyVmk1XLzWYqTA",
    netWeight: "1000g",
    price: 370,
    originalPrice: 400,
    rating: 4.9,
    ratingCount: 395,
    inStock: true,
    cutType: "Thigh Boneless",
    cookingTime: "15-20 Mins",
    benefits: ["Maximum juiciness in every bite", "Never dries out during high heat grill", "100% boneless"],
  },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id || p.id.toLowerCase() === id.toLowerCase());
}

export function getRelatedProducts(currentProduct: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.id !== currentProduct.id && (p.category === currentProduct.category || p.isBestseller)
  ).slice(0, limit);
}

// ─── Live Backend API Fetchers ────────────────────────────────────────────────
import api from "./api";

export async function fetchCategories(): Promise<Category[]> {
  try {
    const { data } = await api.get<{ success: boolean; categories: Category[] }>("/categories");
    if (data.success && data.categories && data.categories.length > 0) {
      // Add "All Items" tab at the beginning
      const allItem: Category = {
        id: "all",
        slug: "all",
        name: "All Items",
        tagline: "Fresh Daily Catch & Cuts",
        icon: "🥩",
        image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
      };
      return [allItem, ...data.categories];
    }
  } catch (err) {
    console.warn("Backend categories unavailable, using local cache:", err);
  }
  return CATEGORIES;
}

export async function fetchProducts(filters?: {
  category?: string;
  search?: string;
  bestseller?: boolean;
  sort?: string;
  limit?: number;
}): Promise<Product[]> {
  try {
    const params = new URLSearchParams();
    if (filters?.category && filters.category !== "all") params.append("category", filters.category);
    if (filters?.search) params.append("search", filters.search);
    if (filters?.bestseller) params.append("bestseller", "true");
    if (filters?.sort) params.append("sort", filters.sort);
    if (filters?.limit) params.append("limit", filters.limit.toString());

    const { data } = await api.get<{ success: boolean; products: Product[] }>(
      `/products?${params.toString()}`
    );
    if (data.success && Array.isArray(data.products)) {
      return data.products;
    }
  } catch (err) {
    console.warn("Backend products unavailable, using local cache:", err);
  }

  // Fallback to local filtering
  let list = [...PRODUCTS];
  if (filters?.category && filters.category !== "all") {
    list = list.filter((p) => p.category === filters.category);
  }
  if (filters?.bestseller) {
    list = list.filter((p) => p.isBestseller);
  }
  if (filters?.search) {
    const q = filters.search.toLowerCase();
    list = list.filter((p) => p.name.toLowerCase().includes(q) || p.description.toLowerCase().includes(q));
  }
  return list;
}

export async function fetchProductById(id: string): Promise<{ product: Product; related: Product[] } | null> {
  try {
    const { data } = await api.get<{ success: boolean; product: Product; related: Product[] }>(
      `/products/${id}`
    );
    if (data.success && data.product) {
      return { product: data.product, related: data.related || [] };
    }
  } catch (err) {
    console.warn(`Backend product ${id} unavailable, using local cache:`, err);
  }

  const p = getProductById(id);
  if (p) {
    return { product: p, related: getRelatedProducts(p) };
  }
  return null;
}

