name: rider_app
description: "TeFFe's Artisanal Fresh Butchery Rider & Delivery Partner Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Networking & REST API
  dio: ^5.4.3+1

  # Local Persistence
  shared_preferences: ^2.2.3

  # Fonts & Typography (Plus Jakarta Sans & Inter)
  google_fonts: ^6.2.1

  # Caching Images & SVG
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Utility & Formatting
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
