/**
 * Seed data for Teffe's MongoDB Atlas Database
 */

const categories = [
  {
    slug: 'chicken',
    name: 'Fresh Chicken',
    tagline: 'Tender, antibiotic-free & cut fresh',
    icon: '🍗',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=400&q=80',
    order: 1,
    isActive: true,
  },
  {
    slug: 'mutton',
    name: 'Rich Mutton',
    tagline: 'Farm-raised goat, tender curry cuts',
    icon: '🍖',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80',
    order: 2,
    isActive: true,
  },
  {
    slug: 'fish',
    name: 'Fish & Seafood',
    tagline: 'Freshwater & sea fish, cleaned & gutted',
    icon: '🐟',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
    order: 3,
    isActive: true,
  },
  {
    slug: 'desi-chicken',
    name: 'Desi Chicken',
    tagline: 'Free-range country chicken (देसी मुर्गा)',
    icon: '🐓',
    image: 'https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=400&q=80',
    order: 4,
    isActive: true,
  },
  {
    slug: 'eggs',
    name: 'Farm Eggs',
    tagline: 'Classic white, brown & country eggs',
    icon: '🥚',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=400&q=80',
    order: 5,
    isActive: true,
  },
];

const products = [
  {
    id: 'prod-chk-1',
    name: 'Fresh Chicken Curry Cut (Skinless)',
    hindiName: 'ताज़ा चिकन करी कट',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Juicy bone-in & boneless pieces of fresh chicken. Cut right after you place your order for unmatched freshness.',
    pieces: '12-16 Pieces',
    serves: '3-4 People',
    badge: 'Bestseller',
    isBestseller: true,
    image: 'https://www.giggsmeat.com/wp-content/uploads/2020/10/rsz_chicken_curry_cut.jpg',
    images: [
      'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80',
    ],
    netWeight: '500g',
    grossWeight: '520g',
    price: 139,
    originalPrice: 170,
    rating: 4.8,
    ratingCount: 342,
    inStock: true,
    cutType: 'Curry Cut',
    cookingTime: '25-30 Mins',
    benefits: ['Even blend of breast & leg pieces', 'High protein & natural tenderness', 'RO washed'],
  },
  {
    id: 'prod-chk-2',
    name: 'Fresh Chicken Breast (Boneless)',
    hindiName: 'बोनलेस चिकन ब्रेस्ट',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Lean, tender and high protein boneless fillets. Ideal for grilling, salads, butter chicken or gym diet.',
    pieces: '2-4 Fillets',
    serves: '2-3 People',
    badge: 'High Protein',
    isBestseller: true,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=900&q=80',
    images: [
      'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80',
    ],
    netWeight: '500g',
    grossWeight: '510g',
    price: 179,
    originalPrice: 220,
    rating: 4.9,
    ratingCount: 280,
    inStock: true,
    cutType: 'Boneless Fillet',
    cookingTime: '12-15 Mins',
    benefits: ['Zero fat & zero bones', '31g protein per 100g', 'Pre-trimmed & ready to cook'],
  },
  {
    id: 'prod-chk-5',
    name: 'Chicken Lollipop 1kg',
    hindiName: 'चिकन लॉलीपॉप (१ किग्रा)',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'You will get 20 to 25 succulent and perfectly shaped pieces in a Kg. Every piece is precisely cut by stainless steel cutting machines and washed in purified RO water.',
    pieces: '20-25 Pieces',
    serves: '4-5 People',
    badge: 'Special Cut',
    isBestseller: true,
    image: 'https://media.istockphoto.com/id/1255992885/photo/raw-lollipop-chicken-wings.jpg?s=612x612&w=0&k=20&c=0Y2W2Mqy6YdN3ZgMvrMpOPYVbD4lHZyKO5nBA16zDd0=',
    images: [
      'https://images.unsplash.com/photo-1527477321055-43615b629c95?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80',
    ],
    netWeight: '1kg',
    grossWeight: '1.05kg',
    price: 285,
    originalPrice: 300,
    rating: 4.8,
    ratingCount: 388,
    inStock: true,
    cutType: 'Lollipop Frenched Cut',
    cookingTime: '15-20 Mins (Fry/Grill)',
    benefits: [
      '20 to 25 frenched winglet pieces per pack',
      'Cut after you place order (0% frozen)',
      'RO water sanitized & packed in food-grade tray',
      'Ideal for crispy starters, Schezwan lollipops & BBQ',
    ],
  },
  {
    id: 'chicken-curry-cut-1kg',
    name: 'Curry Cut 1 Kg',
    hindiName: 'चिकन करी कट (१ किग्रा)',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Mix of bone-in & boneless prime pieces ideal for slow Sunday gravies. Cut after order from healthy broiler chickens, sanitized in RO water.',
    pieces: '14-16 Pieces',
    serves: '4-5 People',
    badge: 'Best Seller',
    isBestseller: true,
    image: 'https://www.giggsmeat.com/wp-content/uploads/2020/10/rsz_chicken_curry_cut.jpg',
    images: [
      'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80',
    ],
    netWeight: '1000g',
    grossWeight: '1050g',
    price: 280,
    originalPrice: 300,
    rating: 4.9,
    ratingCount: 420,
    inStock: true,
    cutType: 'Bone-in Curry Cut',
    cookingTime: '30-35 Mins',
    benefits: ['Balanced leg & breast portions', 'RO-purified wash', 'Never frozen (0-4°C)'],
  },
  {
    id: 'chicken-whole-1kg',
    name: 'Chicken Whole 1kg',
    hindiName: 'साबुत चिकन',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Cleaned, dressed whole chicken without skin. Perfect for whole tandoori roast, rotisserie or custom home butchering.',
    pieces: 'Whole Bird',
    serves: '3-4 People',
    badge: 'Whole Roast',
    isBestseller: false,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1XzvcaeOH9nTHzVUinepJYQIwnsfZZOepX1jRYAfuyvIpLGu93x2ZmCQo52becW2q34ANvzhDL6MFn7LWBzwK5DaMliTgdZb9Vp6VR1Fk2EXPAqVHKR48ZeUQzLTa7zWKQyhVjJj__YDHLxIWgkKbogvTIvg4U5ngY4eXisUnsP9adJsKKfp2c0g2ckloVEf6VjmpOEaEdwvj6aNgdxHpsB7cty010vHxjQoDXXbZjcLi3DEbKIw962pA',
    images: [],
    netWeight: '1000g',
    grossWeight: '1200g',
    price: 280,
    originalPrice: 300,
    rating: 4.7,
    ratingCount: 160,
    inStock: true,
    cutType: 'Whole Dressed',
    cookingTime: '45-60 Mins',
    benefits: ['100% fresh gutless bird', 'Hygienically dressed', 'Perfect for roast & broth'],
  },
  {
    id: 'prod-chk-3',
    name: 'Chicken Biryani Cut (Large Pieces)',
    hindiName: 'बिरयानी कट चिकन',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Specially selected large drumsticks, thigh and breast pieces crafted specifically for authentic dum biryani.',
    pieces: '6-8 Large Pieces',
    serves: '4 People',
    badge: 'Biryani Special',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=80',
    netWeight: '1kg',
    grossWeight: '1.05kg',
    price: 269,
    originalPrice: 320,
    rating: 4.7,
    ratingCount: 195,
    inStock: true,
    cutType: 'Large Cut',
    cookingTime: '40 Mins (Dum Cooking)',
    benefits: ['Large juicy cuts hold marinade perfectly', 'Juicy texture under steam', 'Cut fresh'],
  },
  {
    id: 'prod-chk-4',
    name: 'Chicken Whole Leg (Thigh & Drumstick)',
    hindiName: 'चिकन लेग पीस',
    category: 'chicken',
    categoryLabel: 'Chicken',
    description: 'Tender skinless whole leg pieces with bone. Best for slow-cooked tandoori roasts, curry and fries.',
    pieces: '3-4 Pieces',
    serves: '2-3 People',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '530g',
    price: 159,
    originalPrice: 195,
    rating: 4.8,
    ratingCount: 142,
    inStock: true,
    cutType: 'Leg Piece',
    cookingTime: '25 Mins',
    benefits: ['Succulent dark meat flavor', 'Ideal for tandoor & roast', 'Trimmed of excess fat'],
  },
  {
    id: 'prod-mut-1',
    name: 'Fresh Goat Mutton Curry Cut (Khaste Mutton)',
    hindiName: 'ताज़ा बकरे का मीट करी कट',
    category: 'mutton',
    categoryLabel: 'Mutton',
    description: 'Premium pasture-raised young goat meat with equal blend of bone and meat chunks. Freshly cut on order.',
    pieces: '14-18 Pieces',
    serves: '3-4 People',
    badge: "Chef's Choice",
    isBestseller: true,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '540g',
    price: 439,
    originalPrice: 499,
    rating: 4.9,
    ratingCount: 418,
    inStock: true,
    cutType: 'Curry Cut',
    cookingTime: '45-60 Mins',
    benefits: ['Young grass-fed Khasi goat meat', 'Even fat-to-meat ratio', 'Mouth-melting curry texture'],
  },
  {
    id: 'prod-mut-2',
    name: 'Prime Mutton Shoulder Cut (Bone-In)',
    hindiName: 'मटन शोल्डर कट',
    category: 'mutton',
    categoryLabel: 'Mutton',
    description: 'Rich, tender shoulder cuts known for high marbling and melt-in-mouth texture when slow-cooked in gravy.',
    pieces: '12-15 Pieces',
    serves: '3 People',
    badge: 'Extra Tender',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '520g',
    price: 479,
    originalPrice: 530,
    rating: 4.9,
    ratingCount: 164,
    inStock: true,
    cutType: 'Shoulder Cut',
    cookingTime: '50 Mins',
    benefits: ['High marbling', 'Tender bone marrow flavor', 'Finest cut for Rogan Josh'],
  },
  {
    id: 'prod-mut-3',
    name: 'Fine Goat Mutton Keema (Mince)',
    hindiName: 'बकरे का मटन कीमा',
    category: 'mutton',
    categoryLabel: 'Mutton',
    description: 'Finely ground fresh mutton from prime boneless cuts. Free of excess fat, ideal for kebabs and keema matar.',
    pieces: 'Ground Mince',
    serves: '3-4 People',
    image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '510g',
    price: 499,
    originalPrice: 560,
    rating: 4.8,
    ratingCount: 96,
    inStock: true,
    cutType: 'Keema',
    cookingTime: '25 Mins',
    benefits: ['100% pure meat mince', 'Zero grit or sinew', 'Ideal for Shammi Kebabs & Keema Pav'],
  },
  {
    id: 'prod-fsh-1',
    name: 'Fresh Rohu Fish - Bengali Cut (Cleaned)',
    hindiName: 'रोहू मछली (बंगाली कट)',
    category: 'fish',
    categoryLabel: 'Fish & Seafood',
    description: 'Fresh river catch Rohu, scaled, gutted, and cut into neat steaks and head for delicious fish curry.',
    pieces: '6-8 Steaks + Head',
    serves: '2-3 People',
    badge: 'Daily Catch',
    isBestseller: true,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '650g',
    price: 189,
    originalPrice: 230,
    rating: 4.7,
    ratingCount: 220,
    inStock: true,
    cutType: 'Steaks (Bengali Cut)',
    cookingTime: '15-20 Mins',
    benefits: ['River fresh daily catch', 'Scaled and gutted thoroughly', 'Zero chemical preservatives'],
  },
  {
    id: 'prod-fsh-2',
    name: 'Catla Fish - Medium Steaks (Cleaned)',
    hindiName: 'कतला मछली कट',
    category: 'fish',
    categoryLabel: 'Fish & Seafood',
    description: 'Sweet water Catla steaks. Thoroughly washed with RO water and vacuum packed with temperature control.',
    pieces: '7-9 Steaks',
    serves: '3-4 People',
    image: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=900&q=80',
    netWeight: '500g',
    grossWeight: '620g',
    price: 199,
    originalPrice: 240,
    rating: 4.6,
    ratingCount: 130,
    inStock: true,
    cutType: 'Curry Cut',
    cookingTime: '15 Mins',
    benefits: ['Sweet water taste', 'Rich in Omega 3', 'Cleaned & gutted'],
  },
  {
    id: 'prod-fsh-3',
    name: 'Fresh Sea Prawns - Tail On (Cleaned & Deveined)',
    hindiName: 'ताज़ा झींगा (प्रॉन्स)',
    category: 'fish',
    categoryLabel: 'Fish & Seafood',
    description: 'Large succulent prawns, deshelled and deveined for effortless cooking. No chemical preservatives.',
    pieces: '20-25 Prawns',
    serves: '2-3 People',
    badge: 'Ready to Cook',
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=900&q=80',
    netWeight: '250g',
    grossWeight: '400g',
    price: 289,
    originalPrice: 340,
    rating: 4.9,
    ratingCount: 184,
    inStock: true,
    cutType: 'Deveined',
    cookingTime: '6-8 Mins',
    benefits: ['100% Deveined & peeled', 'Sweet juicy texture', 'High in protein & zinc'],
  },
  {
    id: 'prod-desi-1',
    name: 'Original Desi Country Chicken (देसी मुर्गा)',
    hindiName: 'असली देसी मुर्गा करी कट',
    category: 'desi-chicken',
    categoryLabel: 'Desi Chicken',
    description: 'Authentic naturally reared free-range country chicken. Firm texture, earthy aroma, and deep traditional flavour.',
    pieces: '12-16 Pieces',
    serves: '3-4 People',
    badge: '100% Free Range',
    isBestseller: true,
    image: 'https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=900&q=80',
    netWeight: '1kg',
    grossWeight: '1.2kg',
    price: 469,
    originalPrice: 550,
    rating: 4.9,
    ratingCount: 310,
    inStock: true,
    cutType: 'Skinless Country Cut',
    cookingTime: '45-55 Mins',
    benefits: ['Free-range farm birds', 'Deep earthy flavour', 'Zero hormones or growth steroids'],
  },
  {
    id: 'prod-egg-1',
    name: 'Farm Fresh Classic White Eggs (Pack of 12)',
    hindiName: 'फार्म फ्रेश अंडे (12 पीस)',
    category: 'eggs',
    categoryLabel: 'Eggs',
    description: 'Freshly harvested antibiotic-free table eggs with vibrant yellow yolk. Cleaned and safe packaging.',
    pieces: '12 Eggs',
    serves: 'Daily Essentials',
    badge: 'Daily Fresh',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=900&q=80',
    netWeight: '12 pcs',
    price: 99,
    originalPrice: 120,
    rating: 4.8,
    ratingCount: 520,
    inStock: true,
    cutType: 'Tray Pack',
    benefits: ['Fresh harvest daily', 'Strong shells & rich yolk', 'Hygienically sorted'],
  },
  {
    id: 'prod-egg-2',
    name: 'Nutritious Desi Brown Eggs (Pack of 6)',
    hindiName: 'देसी मुर्गी के भूरे अंडे (6 पीस)',
    category: 'eggs',
    categoryLabel: 'Eggs',
    description: 'Rich in omega-3 and proteins from naturally forage-fed hens. Deep orange yolk and thicker shells.',
    pieces: '6 Eggs',
    serves: 'High Nutrition',
    badge: 'Desi Organic',
    image: 'https://images.unsplash.com/photo-1516448620398-c5f44bf9f441?auto=format&fit=crop&w=900&q=80',
    netWeight: '6 pcs',
    price: 85,
    originalPrice: 105,
    rating: 4.9,
    ratingCount: 245,
    inStock: true,
    cutType: 'Tray Pack',
    benefits: ['Omega-3 fortified', 'Deep golden orange yolk', 'From naturally forage-fed hens'],
  },
  {
    id: 'prod-egg-3',
    name: 'Family Saver Fresh White Eggs (Crate of 30)',
    hindiName: 'फार्म फ्रेश अंडे क्रेट (30 पीस)',
    category: 'eggs',
    categoryLabel: 'Eggs',
    description: 'Economy wholesale family pack of 30 farm-fresh table eggs. Clean, intact, and safe crate packaging.',
    pieces: '30 Eggs',
    serves: 'Family Saver',
    badge: 'Value Crate',
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=900&q=80',
    netWeight: '30 pcs',
    price: 230,
    originalPrice: 270,
    rating: 4.9,
    ratingCount: 410,
    inStock: true,
    cutType: 'Crate Pack',
    benefits: ['Best price per egg', 'Daily fresh sorting', 'Safe shockproof packaging'],
  },
];

const users = [
  {
    name: 'Teffes Super Admin',
    email: 'superadmin@teffes.com',
    password: 'Super@12345',
    phone: '+919876543213',
    role: 'superadmin',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Teffes Admin',
    email: 'admin@teffes.com',
    password: 'Admin@12345',
    phone: '+919876543214',
    role: 'superadmin',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Rahul Sharma',
    email: 'storeadmin@teffes.com',
    password: 'Store@12345',
    phone: '+919876543212',
    role: 'storeadmin',
    storeId: 'S001',
    storeName: 'TeFFe\'s — Kishore Ganj',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Ravi Kumar',
    email: 'rider@teffes.com',
    password: 'Rider@12345',
    phone: '+919876543211',
    role: 'rider',
    vehicleNumber: 'JH01-EC-4821',
    riderStatus: 'Available',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Ankit Sharma',
    email: 'customer@teffes.com',
    password: 'Customer@12345',
    phone: '+919876543210',
    role: 'customer',
    isVerified: true,
    isActive: true,
    addresses: [
      {
        tag: 'Home',
        line1: 'Flat 402, Shivalik Heights, Kishore Ganj Chowk',
        line2: 'Harmu Road',
        city: 'Ranchi',
        pincode: '834001',
        landmark: 'Near Hanuman Mandir',
        isDefault: true,
      },
    ],
  },
];

const stores = [
  {
    storeId: 'S001',
    name: 'TeFFe\'s — Kishore Ganj',
    city: 'Ranchi',
    address: 'Plot 42, Main Road, Kishore Ganj, Ranchi, Jharkhand 834001',
    admin: 'Rahul Sharma',
    adminEmail: 'storeadmin@teffes.com',
    phone: '+91 9779687955',
    status: 'Active',
    orders: 187,
  },
  {
    storeId: 'S002',
    name: 'TeFFe\'s — Doranda Hub',
    city: 'Ranchi',
    address: 'Doranda Bazar, Near High Court, Ranchi, Jharkhand 834002',
    admin: 'Priya Singh',
    adminEmail: 'priya@teffes.com',
    phone: '+91 9279682955',
    status: 'Active',
    orders: 125,
  },
  {
    storeId: 'S003',
    name: 'TeFFe\'s — Harmu Road',
    city: 'Ranchi',
    address: 'Harmu Housing Colony, Ranchi, Jharkhand 834002',
    admin: '—',
    adminEmail: '',
    phone: '—',
    status: 'Planned',
    orders: 0,
  },
];

const orders = [
  {
    orderId: 'TEF-3812',
    customer: {
      name: 'Ankit Sharma',
      phone: '+91 98765 43210',
      address: 'Near Hanuman Mandir, Kishore Ganj, Ranchi',
    },
    items: [
      { productId: 'prod-chk-1', name: 'Fresh Chicken Curry Cut', price: 139, quantity: 2, netWeight: '500g' },
    ],
    amount: 278,
    status: 'Pending',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3811',
    customer: {
      name: 'Sunita Devi',
      phone: '+91 87654 32109',
      address: 'Lalpur, Ranchi',
    },
    items: [
      { productId: 'prod-mut-1', name: 'Fresh Goat Mutton Curry Cut', price: 419, quantity: 1, netWeight: '500g' },
    ],
    amount: 419,
    status: 'Cutting',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3810',
    customer: {
      name: 'Rahul Kumar',
      phone: '+91 76543 21098',
      address: 'Doranda, Ranchi',
    },
    items: [
      { productId: 'prod-fsh-1', name: 'Fresh Rohu Fish - Bengali Cut', price: 189, quantity: 1, netWeight: '500g' },
    ],
    amount: 189,
    status: 'Out for Delivery',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '4:00 PM - 5:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3809',
    customer: {
      name: 'Pooja Gupta',
      phone: '+91 65432 10987',
      address: 'Argora, Ranchi',
    },
    items: [
      { productId: 'prod-desi-1', name: 'Original Desi Country Chicken', price: 429, quantity: 1, netWeight: '1kg' },
    ],
    amount: 429,
    status: 'Ready',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'Online',
    paymentStatus: 'Paid',
  },
  {
    orderId: 'TEF-3808',
    customer: {
      name: 'Vijay Singh',
      phone: '+91 54321 09876',
      address: 'Kantatoli, Ranchi',
    },
    items: [
      { productId: 'prod-chk-5', name: 'Chicken Lollipop 1kg', price: 299, quantity: 1, netWeight: '1kg' },
    ],
    amount: 299,
    status: 'Delivered',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '1:00 PM - 2:30 PM',
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Paid',
  },
  {
    orderId: 'TEF-3807',
    customer: {
      name: 'Meena Kumari',
      phone: '+91 43210 98765',
      address: 'Booty More, Ranchi',
    },
    items: [
      { productId: 'prod-egg-1', name: 'Farm Fresh Classic White Eggs', price: 150, quantity: 2, netWeight: '12 pcs' },
    ],
    amount: 150,
    status: 'Delivered',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '12:00 PM - 1:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
  },
];

const inventory = [
  { itemId: 'INV-001', item: 'Chicken Curry Cut (Skinless)', category: 'Chicken', stock: 98, min: 20, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-002', item: 'Chicken Breast Boneless', category: 'Chicken', stock: 45, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-003', item: 'Chicken Lollipop Cuts', category: 'Chicken', stock: 32, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-004', item: 'Chicken Biryani Cut', category: 'Chicken', stock: 60, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-005', item: 'Goat Mutton Curry Cut', category: 'Mutton', stock: 42, min: 30, unit: 'kg', status: 'Low Stock', lastRestocked: 'Yesterday 5:00 PM', storeId: 'S001' },
  { itemId: 'INV-006', item: 'Prime Mutton Shoulder', category: 'Mutton', stock: 18, min: 15, unit: 'kg', status: 'Low Stock', lastRestocked: 'Yesterday 5:00 PM', storeId: 'S001' },
  { itemId: 'INV-007', item: 'Fine Mutton Keema', category: 'Mutton', stock: 14, min: 10, unit: 'kg', status: 'Low Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-008', item: 'Fresh Rohu Fish (River)', category: 'Fish', stock: 35, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-009', item: 'Catla Fish Steaks', category: 'Fish', stock: 22, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-010', item: 'Sea Prawns Deveined', category: 'Fish', stock: 16, min: 8, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-011', item: 'Desi Country Chicken', category: 'Desi Chicken', stock: 28, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-012', item: 'Farm Fresh White Eggs', category: 'Eggs', stock: 480, min: 100, unit: 'pcs', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-013', item: 'Desi Brown Eggs', category: 'Eggs', stock: 120, min: 40, unit: 'pcs', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
];

const deliverySlots = [
  { slot: '07:00 AM – 09:00 AM (Early Morning)', capacity: 25, booked: 24, riders: 3, status: 'Almost Full', storeId: 'S001' },
  { slot: '09:00 AM – 11:00 AM (Morning Prime)', capacity: 35, booked: 31, riders: 4, status: 'Almost Full', storeId: 'S001' },
  { slot: '11:00 AM – 01:00 PM (Lunch Rush)', capacity: 40, booked: 28, riders: 4, status: 'Filling Fast', storeId: 'S001' },
  { slot: '01:00 PM – 03:00 PM (Afternoon)', capacity: 20, booked: 9, riders: 2, status: 'Open', storeId: 'S001' },
  { slot: '03:00 PM – 05:00 PM (Evening Prime)', capacity: 35, booked: 18, riders: 3, status: 'Open', storeId: 'S001' },
  { slot: '05:00 PM – 07:00 PM (Dinner Rush)', capacity: 40, booked: 22, riders: 4, status: 'Filling Fast', storeId: 'S001' },
  { slot: '07:00 PM – 09:00 PM (Night Slots)', capacity: 30, booked: 7, riders: 2, status: 'Open', storeId: 'S001' },
];

const returnRequests = [
  {
    requestId: 'RET-019',
    orderId: 'TEF-3801',
    customer: 'Priya Singh',
    phone: '+91 98765 11223',
    items: 'Goat Mutton Curry Cut (500g)',
    reason: 'Bone proportion higher than standard ratio',
    condition: 'Reported within 22 mins, chilled & intact in tray',
    status: 'Exchange Dispatched',
    storeId: 'S001',
  },
  {
    requestId: 'RET-018',
    orderId: 'TEF-3794',
    customer: 'Vikram Sahay',
    phone: '+91 94311 55667',
    items: 'Chicken Breast Boneless (500g)',
    reason: 'Ordered curry cut by mistake, requesting replacement',
    condition: 'Tray seal opened at delivery doorstep',
    status: 'Approved',
    storeId: 'S001',
  },
  {
    requestId: 'RET-017',
    orderId: 'TEF-3788',
    customer: 'Rashmi Verma',
    phone: '+91 87654 99881',
    items: 'Rohu Fish Bengali Cut (500g)',
    reason: 'Cut pieces smaller than requested preference',
    condition: 'Reported within 45 mins, packed in insulated bag',
    status: 'Completed',
    storeId: 'S001',
  },
];

const coupons = [
  {
    code: 'FIRST50',
    discount: '₹50 flat off on first order above ₹299',
    discountType: 'fixed',
    discountValue: 50,
    minOrder: 299,
    used: 842,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
  {
    code: 'FRESH10',
    discount: '10% instant discount on orders above ₹499',
    discountType: 'percentage',
    discountValue: 10,
    minOrder: 499,
    used: 512,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
  {
    code: 'TEFFESFREE',
    discount: '100% Free express delivery on orders above ₹399',
    discountType: 'free_delivery',
    discountValue: 40,
    minOrder: 399,
    used: 1204,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
];

module.exports = {
  categories,
  products,
  users,
  stores,
  orders,
  inventory,
  deliverySlots,
  returnRequests,
  coupons,
};
