/**
 * Seed data for Teffe's MongoDB Atlas Database
 */

const categories = [
  {
    slug: 'chicken',
    name: 'Fresh Chicken',
    tagline: 'Tender, antibiotic-free & cut fresh',
    icon: '🍗',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=400&q=80',
    order: 1,
    isActive: true,
  },
  {
    name: 'Rich Mutton',
    slug: 'mutton',
    description: 'Tender, farm-raised goat & lamb cuts for rich curries and biryanis.',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
    isActive: true,
  },
  {
    slug: 'fish',
    name: 'Fish & Seafood',
    tagline: 'Freshwater & sea fish, cleaned & gutted',
    icon: '🐟',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
    order: 3,
    isActive: true,
  },
  {
    slug: 'desi-chicken',
    name: 'Desi Chicken',
    tagline: 'Free-range country chicken (देसी मुर्गा)',
    icon: '🐓',
    image: 'https://images.unsplash.com/photo-1548567117-0429f43f119a?auto=format&fit=crop&w=400&q=80',
    order: 4,
    isActive: true,
  },
  {
    slug: 'eggs',
    name: 'Farm Eggs',
    tagline: 'Classic white, brown & country eggs',
    icon: '🥚',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=400&q=80',
    order: 5,
    isActive: true,
  },
];

const products = [
  {
    "id": "prod-28643425",
    "name": "Chicken Lollipop 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "you will get 20 to 25 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine.",
    "pieces": "20 to 25 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/LtbiqVBO.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/LtbiqVBO.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/0pgc2GLI.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 285,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 152,
    "inStock": true,
    "cutType": "Lollipop Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643429",
    "name": "Curry Cut 1 Kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "live chicken weight is not more than 1.5 Kg.\nfreshly cut on order only.\nminimum 20 standard pieces will be in a Kg with liver pot.\nEvery piece is precisely cut by stainless steel cutting machine. there will not be any neck or rib cage in curry cut.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/D6Bcya2p.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/D6Bcya2p.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 154,
    "inStock": true,
    "cutType": "Curry Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643433",
    "name": "Chicken With Skin Hole. 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "live chicken weight is not more than 1.5 Kg.\nfreshly prepared after receiving order only.\nEvery piece is precisely cut by stainless steel cutting machine.\nminimum 20 pis in a kg., there will not be neck and rib cage in curry cut.",
    "pieces": "20 Pieces",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/dh2PpCdQ.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/dh2PpCdQ.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/FvsQA3W4.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 280,
    "rating": 4.8,
    "ratingCount": 175,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643442",
    "name": "Chicken Liver 1 Kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 15 to 18 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine",
    "pieces": "15 to 18 Pieces",
    "serves": "4-5 People",
    "badge": "Trending",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/68zHYLOh.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/68zHYLOh.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/AGLZJKXO.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 265,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 162,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643446",
    "name": "Chicken Drumsticks 1 Kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 10 to 12 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine",
    "pieces": "10 to 12 Pieces",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/QkylxeUe.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/QkylxeUe.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/HDp9L1iF.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 350,
    "originalPrice": 370,
    "rating": 4.8,
    "ratingCount": 202,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643457",
    "name": "Chicken Wings 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 14 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine",
    "pieces": "14 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/5pgtWn2m.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/5pgtWn2m.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 245,
    "originalPrice": 265,
    "rating": 4.8,
    "ratingCount": 90,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643459",
    "name": "Chicken Ran 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 4 to 6 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine",
    "pieces": "4 to 6 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/utbT74IS.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/utbT74IS.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/V8hENXwB.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 290,
    "originalPrice": 310,
    "rating": 4.8,
    "ratingCount": 147,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643461",
    "name": "Chicken Keema 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on your order only.\nEvery piece is precisely chopped by stainless steel knife.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/K9AKxpdn.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/K9AKxpdn.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/KCHWJ4zh.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 370,
    "originalPrice": 385,
    "rating": 4.8,
    "ratingCount": 220,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643463",
    "name": "Chicken Neck 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 4 to 5 full length neck pieces will be in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/njumAvjo.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/njumAvjo.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 130,
    "originalPrice": 150,
    "rating": 4.8,
    "ratingCount": 158,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643468",
    "name": "Chicken Bone 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "uses for chicken soup and pet food",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/rUyOxQfB.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/rUyOxQfB.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/m9MxHJCn.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 65,
    "originalPrice": 75,
    "rating": 4.8,
    "ratingCount": 188,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28646305",
    "name": "Chicken Gori 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 20 pieces in a Kg",
    "pieces": "20 Pieces",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/bHLHNq8x.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/bHLHNq8x.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/xsIoMUfc.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 70,
    "originalPrice": 75,
    "rating": 4.8,
    "ratingCount": 88,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28656084",
    "name": "Skin Brest Boneless 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "skin boneless will test good if prepare in microwave, oven etc..\nEvery piece is precisely cut buy stainless steel cutting machine",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/CDG53vfi.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/CDG53vfi.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 360,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 80,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28658244",
    "name": "Leg Boneless 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Very soft if cooked in tandur . Every piece is precisely cut by stainless steel cutting machine. 25 to 30 pieces will be in a Kg",
    "pieces": "25 to 30 Pieces",
    "serves": "4-5 People",
    "badge": "Trending",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/YyzuS2qW.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/YyzuS2qW.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 370,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 185,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665236",
    "name": "Brest Boneless .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared from healthy chicken intend to provide fresh and healthy brest boneless chilli cut . Approximately 20 pics will be there.",
    "pieces": "20 Pieces",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/EibSLFhV.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/EibSLFhV.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/knEyTrlt.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 200,
    "rating": 4.8,
    "ratingCount": 153,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665244",
    "name": "Chicken Curry Cut 500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Curry Cut 500gm freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/NVIxjGJN.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/NVIxjGJN.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 150,
    "originalPrice": 165,
    "rating": 4.8,
    "ratingCount": 112,
    "inStock": true,
    "cutType": "Curry Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665250",
    "name": "Chicken Liver 500 g",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Liver 500 g freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/CUK62Eyx.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/CUK62Eyx.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/e3K4Wmrb.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 135,
    "originalPrice": 135,
    "rating": 4.8,
    "ratingCount": 93,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665258",
    "name": "Chicken Lolipop 500 g",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Lolipop 500 g freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/3NbvkrwR.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/3NbvkrwR.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/MldxMtRE.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 150,
    "originalPrice": 150,
    "rating": 4.8,
    "ratingCount": 82,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665264",
    "name": "Chicken Drumsticks 500 g",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Drumsticks 500 g freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/JkBhgjWh.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/JkBhgjWh.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/1YCLz1ht.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 220,
    "rating": 4.8,
    "ratingCount": 99,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28665268",
    "name": "Skin Chicken 500 g",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Skin Chicken 500 g freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/hHlN6jYC.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/hHlN6jYC.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/eyaJdlOa.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 150,
    "originalPrice": 165,
    "rating": 4.8,
    "ratingCount": 217,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28683115",
    "name": "Chicken Boneless Keema 500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Boneless Keema 500gm freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/WaVT9nDh.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/WaVT9nDh.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/5fUfUfVx.jpeg"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 200,
    "rating": 4.8,
    "ratingCount": 108,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-28643443",
    "name": "Chicken Pot 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly cut and prepare for home delivery.\nyou will get 20 to 25 pieces in a Kg.\nEvery piece is precisely cut buy stainless steel cutting machine",
    "pieces": "20 to 25 Pieces",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/hkQgN9Lq.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/hkQgN9Lq.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/q6uTWr0j.jpeg"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 265,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 226,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392574",
    "name": "Chicken Tandoori Cut 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed hole chicken precisely cut into 4 pieces . there  will be 6 to 8 pieces in a one kg.",
    "pieces": "4 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/BsBX4yGN.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/BsBX4yGN.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 132,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392621",
    "name": "Chicken Boneless Strips  .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared chicken boneless strips standard 4 to 5 inches long, approximately 10 pieces in a.500gm.",
    "pieces": "10 Pieces",
    "serves": "2-3 People",
    "badge": "Trending",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/KpN7s3NK.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/KpN7s3NK.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 225,
    "rating": 4.8,
    "ratingCount": 198,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392586",
    "name": "Chicken Biryani Cut 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed hole chicken precisely cut into 8 pieces. there will be 12 to 14 pieces in a one kg. no neck will be there.",
    "pieces": "8 Pieces",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/6EW8qrl6.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/6EW8qrl6.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 113,
    "inStock": true,
    "cutType": "Biryani Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392639",
    "name": "Chicken Boneless Tikka Cut .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken boneless tikka  standard 15to 20 pieces in a .500gm.",
    "pieces": "15to 20 Pieces",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/KdHFZJTg.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/KdHFZJTg.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 225,
    "rating": 4.8,
    "ratingCount": 107,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392596",
    "name": "Chicken Hole 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed hole chicken, standard.800gm to .900gm size in a one hole chicken, along with liver and pot.2",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "Trending",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/bMiDbBlp.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/bMiDbBlp.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 184,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392651",
    "name": "Chicken Skin Wings .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Chicken Skin Wings .500gm freshly prepared on order.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/CQxml8JG.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/CQxml8JG.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 145,
    "originalPrice": 165,
    "rating": 4.8,
    "ratingCount": 101,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392616",
    "name": "Chicken Boneless Strips 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared chicken boneless strips . standard 4 to 5 inches long, approximately 20 pieces in a kg.",
    "pieces": "20 Pieces",
    "serves": "4-5 People",
    "badge": "Trending",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/YtELMutl.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/YtELMutl.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 370,
    "originalPrice": 420,
    "rating": 4.8,
    "ratingCount": 172,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392664",
    "name": "Chicken Skin Lollipop .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared chicken skin lollipop standard 12 to 14 pieces in a.500gm.",
    "pieces": "12 to 14 Pieces",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/iACDClRf.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/iACDClRf.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 145,
    "originalPrice": 165,
    "rating": 4.8,
    "ratingCount": 160,
    "inStock": true,
    "cutType": "Lollipop Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392628",
    "name": "Chicken Boneless Tikka Cut",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken boneless, medium size at least 30  to 35 pieces in a kg.",
    "pieces": "30  to 35 Pieces",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/BNM4pUwJ.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/BNM4pUwJ.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 370,
    "originalPrice": 420,
    "rating": 4.8,
    "ratingCount": 170,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392677",
    "name": "Chicken Skin Drumsticks .500gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken drumsticks standard 5 pieces in a.500gm.",
    "pieces": "5 Pieces",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/tMn1H0u4.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/tMn1H0u4.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 200,
    "originalPrice": 220,
    "rating": 4.8,
    "ratingCount": 205,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392647",
    "name": "Chicken Skin Wings 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared chicken skin wings , standard 16 pieces in a one kg.",
    "pieces": "16 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/CBHtlkjA.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/CBHtlkjA.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 245,
    "originalPrice": 280,
    "rating": 4.8,
    "ratingCount": 93,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392659",
    "name": "Chicken Skin Lollipop 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared chicken skin lollipop standard 20 to 25 pieces in a one kg.",
    "pieces": "20 to 25 Pieces",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/QKZCNkDH.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/QKZCNkDH.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 290,
    "originalPrice": 320,
    "rating": 4.8,
    "ratingCount": 99,
    "inStock": true,
    "cutType": "Lollipop Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392671",
    "name": "Chicken Skin Drumstick 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken skin drumsticks standard 10 pieces in a one kg.",
    "pieces": "10 Pieces",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/CIkdhs7R.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/CIkdhs7R.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 340,
    "originalPrice": 370,
    "rating": 4.8,
    "ratingCount": 85,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32392687",
    "name": "Chicken Skin Curry Cut 1",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken skin curry cut. standard 15 pieces in a one kg.",
    "pieces": "15 Pieces",
    "serves": "2-3 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/cF4Lm7pW.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/cF4Lm7pW.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 285,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 166,
    "inStock": true,
    "cutType": "Curry Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32426605",
    "name": "Breast Boneless Hole 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared from healthy chicken intend to provide fresh and healthy chicken breast boneless. Approximately 3 to 4 hole pics will be there.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/kkd6YQ54.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/kkd6YQ54.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 370,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 143,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32426615",
    "name": "Breast Boneless Chilli Cut 1kg",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared from healthy chicken intend to provide fresh and healthy brest boneless. Approximately 50 pics in a kg.",
    "pieces": "50 Pieces",
    "serves": "4-5 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/PE24XFjY.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/PE24XFjY.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 370,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 169,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095921",
    "name": "Curry Cut 750gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "live chicken weight is not more than 1.5 Kg.\nfreshly cut on order only.\nminimum 20 standard pieces will be in a Kg with liver pot.\nEvery piece is precisely cut by stainless steel cutting machine. there will not be any neck or rib cage in curry cut.",
    "pieces": "",
    "serves": "3-4 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/D6Bcya2p.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/D6Bcya2p.jpeg"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 220,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 218,
    "inStock": true,
    "cutType": "Curry Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095922",
    "name": "Chicken Keema 750gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on your order only.\nEvery piece is precisely chopped by stainless steel knife.",
    "pieces": "",
    "serves": "3-4 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/K9AKxpdn.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/K9AKxpdn.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/KCHWJ4zh.jpeg"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 290,
    "originalPrice": 385,
    "rating": 4.8,
    "ratingCount": 128,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095924",
    "name": "Chicken Biryani Cut 750 gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed hole chicken precisely cut into 8 pieces. there will be 12 to 14 pieces in a one kg. no neck will be there.",
    "pieces": "8 Pieces",
    "serves": "3-4 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/6EW8qrl6.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/6EW8qrl6.webp"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 220,
    "originalPrice": 300,
    "rating": 4.8,
    "ratingCount": 81,
    "inStock": true,
    "cutType": "Biryani Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095925",
    "name": "Chicken Boneless Tikka Cut 750 gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly dressed and prepare chicken boneless, medium size at least 30  to 35 pieces in a kg.",
    "pieces": "30  to 35 Pieces",
    "serves": "3-4 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/BNM4pUwJ.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/BNM4pUwJ.webp"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 290,
    "originalPrice": 420,
    "rating": 4.8,
    "ratingCount": 119,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095927",
    "name": "Chicken Drumsticks 750gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared on daily basis.\nApprox 10 to 12 pieces in a Kg.\nEvery piece is precisely cut by stainless steel cutting machine",
    "pieces": "10 to 12 Pieces",
    "serves": "3-4 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/QkylxeUe.jpeg",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/QkylxeUe.jpeg",
      "https://cdn.dotpe.in/longtail/store-items/7524323/HDp9L1iF.jpeg"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 265,
    "originalPrice": 370,
    "rating": 4.8,
    "ratingCount": 96,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095928",
    "name": "Breast Boneless Hole  750gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared from healthy chicken intend to provide fresh and healthy chicken breast boneless. Approximately 3 to 4 hole pics will be there.",
    "pieces": "",
    "serves": "3-4 People",
    "badge": "",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/kkd6YQ54.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/kkd6YQ54.webp"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 290,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 160,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095929",
    "name": "Breast Boneless Chilli Cut 750gm",
    "hindiName": "",
    "category": "chicken",
    "categoryLabel": "Fresh Chicken",
    "description": "Freshly prepared from healthy chicken intend to provide fresh and healthy brest boneless. Approximately 50 pics in a kg.",
    "pieces": "50 Pieces",
    "serves": "3-4 People",
    "badge": "Recommended",
    "isBestseller": false,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/PE24XFjY.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/PE24XFjY.webp"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 290,
    "originalPrice": 400,
    "rating": 4.8,
    "ratingCount": 200,
    "inStock": true,
    "cutType": "Boneless Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32847549",
    "name": "Mutton 1Kg",
    "hindiName": "",
    "category": "mutton",
    "categoryLabel": "Rich Mutton",
    "description": "1Kg Pure & Fresh Mutton\n\nPure Desi Black West-Bengal breed, Native breed of Panch Pargana (Jharkhand & Bengal). Good Taste, Healthy Red Meat, Locally Procured.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/h4kjPyZH.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/h4kjPyZH.webp",
      "https://cdn.dotpe.in/longtail/store-items/7524323/JJBAPke3.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 900,
    "originalPrice": 1000,
    "rating": 4.8,
    "ratingCount": 201,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32847560",
    "name": "Mutton 500gm",
    "hindiName": "",
    "category": "mutton",
    "categoryLabel": "Rich Mutton",
    "description": "Pure & Fresh Mutton 500 gm\n\nPure Desi Black West-Bengal breed, Native breed of Panch Pargana (Jharkhand & Bengal). Good Taste, Healthy Red Meat, Locally Procured.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/RRrFvXIh.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/RRrFvXIh.webp",
      "https://cdn.dotpe.in/longtail/store-items/7524323/0iOSgRcO.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 500,
    "originalPrice": 550,
    "rating": 4.8,
    "ratingCount": 82,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-33095920",
    "name": "Mutton 750gm",
    "hindiName": "",
    "category": "mutton",
    "categoryLabel": "Rich Mutton",
    "description": "Pure & Fresh Mutton 500 gm\n\nPure Desi Black West-Bengal breed, Native breed of Panch Pargana (Jharkhand & Bengal). Good Taste, Healthy Red Meat, Locally Procured.",
    "pieces": "",
    "serves": "3-4 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/RRrFvXIh.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/RRrFvXIh.webp",
      "https://cdn.dotpe.in/longtail/store-items/7524323/0iOSgRcO.webp"
    ],
    "netWeight": "750g",
    "grossWeight": "800g",
    "price": 750,
    "originalPrice": 800,
    "rating": 4.8,
    "ratingCount": 86,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32847566",
    "name": "Local Rohu Fish 1 Kg",
    "hindiName": "",
    "category": "fish",
    "categoryLabel": "Fish & Seafood",
    "description": "Net Weight after cleaning - 1Kg (No Formalin Treated)\n\nFresh water fish locally sourced and procured, prepared for you after receiving order. Procured from Gola, Petarwar, Bundu and Tamar.",
    "pieces": "",
    "serves": "4-5 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/4e3AEjkv.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/4e3AEjkv.webp",
      "https://cdn.dotpe.in/longtail/store-items/7524323/vHQ97ue4.webp"
    ],
    "netWeight": "1kg",
    "grossWeight": "1.05kg",
    "price": 280,
    "originalPrice": 350,
    "rating": 4.8,
    "ratingCount": 160,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  },
  {
    "id": "prod-32847571",
    "name": "Local Rohu Fish 500gm",
    "hindiName": "",
    "category": "fish",
    "categoryLabel": "Fish & Seafood",
    "description": "Net Weight after cleaning - 500gm (No Formalin Treated)\n\nFresh water fish locally sourced and procured, prepared for you after receiving order. Procured from Gola, Petarwar, Bundu and Tamar.",
    "pieces": "",
    "serves": "2-3 People",
    "badge": "Bestseller",
    "isBestseller": true,
    "image": "https://cdn.dotpe.in/longtail/store-items/7524323/9QADQ3p5.webp",
    "images": [
      "https://cdn.dotpe.in/longtail/store-items/7524323/9QADQ3p5.webp",
      "https://cdn.dotpe.in/longtail/store-items/7524323/cD3ZsoP5.webp"
    ],
    "netWeight": "500g",
    "grossWeight": "550g",
    "price": 145,
    "originalPrice": 200,
    "rating": 4.8,
    "ratingCount": 109,
    "inStock": true,
    "cutType": "Fresh Cut",
    "cookingTime": "15-25 Mins",
    "benefits": [
      "Fresh cut strictly on order (Never Frozen)",
      "Cleaned & washed in purified water",
      "Vacuum-sealed hygienic food-grade pack",
      "Direct doorstep delivery in insulated box"
    ]
  }
];

const users = [
  {
    name: 'Teffes Super Admin',
    email: 'superadmin@teffes.com',
    password: 'Super@12345',
    phone: '+919876543213',
    role: 'superadmin',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Teffes Admin',
    email: 'admin@teffes.com',
    password: 'Admin@12345',
    phone: '+919876543214',
    role: 'superadmin',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Rahul Sharma',
    email: 'storeadmin@teffes.com',
    password: 'Store@12345',
    phone: '+919876543212',
    role: 'storeadmin',
    storeId: 'S001',
    storeName: 'TeFFe\'s — Kishore Ganj',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Ravi Kumar',
    email: 'rider@teffes.com',
    password: 'Rider@12345',
    phone: '+919876543211',
    role: 'rider',
    vehicleNumber: 'JH01-EC-4821',
    riderStatus: 'Available',
    isVerified: true,
    isActive: true,
  },
  {
    name: 'Ankit Sharma',
    email: 'customer@teffes.com',
    password: 'Customer@12345',
    phone: '+919876543210',
    role: 'customer',
    isVerified: true,
    isActive: true,
    addresses: [
      {
        tag: 'Home',
        line1: 'Flat 402, Shivalik Heights, Kishore Ganj Chowk',
        line2: 'Harmu Road',
        city: 'Ranchi',
        pincode: '834001',
        landmark: 'Near Hanuman Mandir',
        isDefault: true,
      },
    ],
  },
];

const stores = [
  {
    storeId: 'S001',
    name: 'TeFFe\'s — Kishore Ganj',
    city: 'Ranchi',
    address: 'Plot 42, Main Road, Kishore Ganj, Ranchi, Jharkhand 834001',
    admin: 'Rahul Sharma',
    adminEmail: 'storeadmin@teffes.com',
    phone: '+91 9779687955',
    status: 'Active',
    orders: 187,
  },
  {
    storeId: 'S002',
    name: 'TeFFe\'s — Doranda Hub',
    city: 'Ranchi',
    address: 'Doranda Bazar, Near High Court, Ranchi, Jharkhand 834002',
    admin: 'Priya Singh',
    adminEmail: 'priya@teffes.com',
    phone: '+91 9279682955',
    status: 'Active',
    orders: 125,
  },
  {
    storeId: 'S003',
    name: 'TeFFe\'s — Harmu Road',
    city: 'Ranchi',
    address: 'Harmu Housing Colony, Ranchi, Jharkhand 834002',
    admin: '—',
    adminEmail: '',
    phone: '—',
    status: 'Planned',
    orders: 0,
  },
];

const orders = [
  {
    orderId: 'TEF-3812',
    customer: {
      name: 'Ankit Sharma',
      phone: '+91 98765 43210',
      address: 'Near Hanuman Mandir, Kishore Ganj, Ranchi',
    },
    items: [
      { productId: 'prod-chk-1', name: 'Fresh Chicken Curry Cut', price: 139, quantity: 2, netWeight: '500g' },
    ],
    amount: 278,
    status: 'Pending',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3811',
    customer: {
      name: 'Sunita Devi',
      phone: '+91 87654 32109',
      address: 'Lalpur, Ranchi',
    },
    items: [
      { productId: 'prod-mut-1', name: 'Fresh Goat Mutton Curry Cut', price: 419, quantity: 1, netWeight: '500g' },
    ],
    amount: 419,
    status: 'Cutting',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3810',
    customer: {
      name: 'Rahul Kumar',
      phone: '+91 76543 21098',
      address: 'Doranda, Ranchi',
    },
    items: [
      { productId: 'prod-fsh-1', name: 'Fresh Rohu Fish - Bengali Cut', price: 189, quantity: 1, netWeight: '500g' },
    ],
    amount: 189,
    status: 'Out for Delivery',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '4:00 PM - 5:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    rider: { name: 'Ravi Kumar', phone: '+91 98765 43211', vehicleNumber: 'JH01-EC-4821' },
  },
  {
    orderId: 'TEF-3809',
    customer: {
      name: 'Pooja Gupta',
      phone: '+91 65432 10987',
      address: 'Argora, Ranchi',
    },
    items: [
      { productId: 'prod-desi-1', name: 'Original Desi Country Chicken', price: 429, quantity: 1, netWeight: '1kg' },
    ],
    amount: 429,
    status: 'Ready',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '90 Mins Express',
    paymentMethod: 'Online',
    paymentStatus: 'Paid',
  },
  {
    orderId: 'TEF-3808',
    customer: {
      name: 'Vijay Singh',
      phone: '+91 54321 09876',
      address: 'Kantatoli, Ranchi',
    },
    items: [
      { productId: 'prod-chk-5', name: 'Chicken Lollipop 1kg', price: 299, quantity: 1, netWeight: '1kg' },
    ],
    amount: 299,
    status: 'Delivered',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '1:00 PM - 2:30 PM',
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Paid',
  },
  {
    orderId: 'TEF-3807',
    customer: {
      name: 'Meena Kumari',
      phone: '+91 43210 98765',
      address: 'Booty More, Ranchi',
    },
    items: [
      { productId: 'prod-egg-1', name: 'Farm Fresh Classic White Eggs', price: 150, quantity: 2, netWeight: '12 pcs' },
    ],
    amount: 150,
    status: 'Delivered',
    storeId: 'S001',
    storeName: 'Kishore Ganj',
    deliverySlot: '12:00 PM - 1:30 PM',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
  },
];

const inventory = [
  { itemId: 'INV-001', item: 'Chicken Curry Cut (Skinless)', category: 'Chicken', stock: 98, min: 20, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-002', item: 'Chicken Breast Boneless', category: 'Chicken', stock: 45, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-003', item: 'Chicken Lollipop Cuts', category: 'Chicken', stock: 32, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-004', item: 'Chicken Biryani Cut', category: 'Chicken', stock: 60, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-005', item: 'Goat Mutton Curry Cut', category: 'Mutton', stock: 42, min: 30, unit: 'kg', status: 'Low Stock', lastRestocked: 'Yesterday 5:00 PM', storeId: 'S001' },
  { itemId: 'INV-006', item: 'Prime Mutton Shoulder', category: 'Mutton', stock: 18, min: 15, unit: 'kg', status: 'Low Stock', lastRestocked: 'Yesterday 5:00 PM', storeId: 'S001' },
  { itemId: 'INV-007', item: 'Fine Mutton Keema', category: 'Mutton', stock: 14, min: 10, unit: 'kg', status: 'Low Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-008', item: 'Fresh Rohu Fish (River)', category: 'Fish', stock: 35, min: 15, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-009', item: 'Catla Fish Steaks', category: 'Fish', stock: 22, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-010', item: 'Sea Prawns Deveined', category: 'Fish', stock: 16, min: 8, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 5:30 AM', storeId: 'S001' },
  { itemId: 'INV-011', item: 'Desi Country Chicken', category: 'Desi Chicken', stock: 28, min: 10, unit: 'kg', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-012', item: 'Farm Fresh White Eggs', category: 'Eggs', stock: 480, min: 100, unit: 'pcs', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
  { itemId: 'INV-013', item: 'Desi Brown Eggs', category: 'Eggs', stock: 120, min: 40, unit: 'pcs', status: 'In Stock', lastRestocked: 'Today 6:00 AM', storeId: 'S001' },
];

const deliverySlots = [
  { slot: '07:00 AM – 09:00 AM (Early Morning)', capacity: 25, booked: 24, riders: 3, status: 'Almost Full', storeId: 'S001' },
  { slot: '09:00 AM – 11:00 AM (Morning Prime)', capacity: 35, booked: 31, riders: 4, status: 'Almost Full', storeId: 'S001' },
  { slot: '11:00 AM – 01:00 PM (Lunch Rush)', capacity: 40, booked: 28, riders: 4, status: 'Filling Fast', storeId: 'S001' },
  { slot: '01:00 PM – 03:00 PM (Afternoon)', capacity: 20, booked: 9, riders: 2, status: 'Open', storeId: 'S001' },
  { slot: '03:00 PM – 05:00 PM (Evening Prime)', capacity: 35, booked: 18, riders: 3, status: 'Open', storeId: 'S001' },
  { slot: '05:00 PM – 07:00 PM (Dinner Rush)', capacity: 40, booked: 22, riders: 4, status: 'Filling Fast', storeId: 'S001' },
  { slot: '07:00 PM – 09:00 PM (Night Slots)', capacity: 30, booked: 7, riders: 2, status: 'Open', storeId: 'S001' },
];

const returnRequests = [
  {
    requestId: 'RET-019',
    orderId: 'TEF-3801',
    customer: 'Priya Singh',
    phone: '+91 98765 11223',
    items: 'Goat Mutton Curry Cut (500g)',
    reason: 'Bone proportion higher than standard ratio',
    condition: 'Reported within 22 mins, fresh & intact in tray',
    status: 'Exchange Dispatched',
    storeId: 'S001',
  },
  {
    requestId: 'RET-018',
    orderId: 'TEF-3794',
    customer: 'Vikram Sahay',
    phone: '+91 94311 55667',
    items: 'Chicken Breast Boneless (500g)',
    reason: 'Ordered curry cut by mistake, requesting replacement',
    condition: 'Tray seal opened at delivery doorstep',
    status: 'Approved',
    storeId: 'S001',
  },
  {
    requestId: 'RET-017',
    orderId: 'TEF-3788',
    customer: 'Rashmi Verma',
    phone: '+91 87654 99881',
    items: 'Rohu Fish Bengali Cut (500g)',
    reason: 'Cut pieces smaller than requested preference',
    condition: 'Reported within 45 mins, packed in insulated bag',
    status: 'Completed',
    storeId: 'S001',
  },
];

const coupons = [
  {
    code: 'FIRST50',
    discount: '₹50 flat off on first order above ₹299',
    discountType: 'fixed',
    discountValue: 50,
    minOrder: 299,
    used: 842,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
  {
    code: 'FRESH10',
    discount: '10% instant discount on orders above ₹499',
    discountType: 'percentage',
    discountValue: 10,
    minOrder: 499,
    used: 512,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
  {
    code: 'TEFFESFREE',
    discount: '100% Free express delivery on orders above ₹399',
    discountType: 'free_delivery',
    discountValue: 40,
    minOrder: 399,
    used: 1204,
    status: 'Active',
    validTill: '31 Dec 2026',
  },
];

module.exports = {
  categories,
  products,
  users,
  stores,
  orders,
  inventory,
  deliverySlots,
  returnRequests,
  coupons,
};
